### ISSUE TITLE
Not able to associate consumer with a group

### ISSUE THREAD

**Issue by programmer-pragmatic** [Jroland/kafka-net#13]
I was evaluating kafka-client for one of our new project. While testing I found that i cannot associate consumer with a group.
If this is not possible then how could i use kafka as queue.

Apart from that isn't there high level API available?. I could not find such. I wanted to use zookeeper instead of using kafka broker (for instance with consmer).

Thanks In Advance
programmer-pragmatic

**Comment by leinemann** [comment]
Hi, this sounds great! Is there by any chance an example where multiple consumers are sharing the same consumer group?
many thanks,
Christoph

**Comment by Jroland** [comment]
The consumer is pretty basic at the moment.  I was primarily focusing on the producer, and getting that working better.  There is a pull request from aNutForAJarOfTuna, which looks like he does some work implementing a higher level consumer, but I have not pulled anything in to this project yet.  Ill create a new issue for creating a higher level consumer.

**Comment by thook76** [comment]
Hi James,
    is there a way to consume from a topic lets call it topicA, and stop the consumer after the initial read.  I am doing this on start up of my application, on start i consume topicA to get the offsetposition for my mainTopic,  how can i stop topicA after the initial read?

I am using Kafka-Net 0.9.0.65
