### ISSUE TITLE
Unable to implement Kafka queuing with MVC application (Web appliaction)

### ISSUE THREAD

**Issue by anshul-rastogi** [Jroland/kafka-net#18]
Hi, 

I am trying to implement kafka in my MVC application. So used the kafka-net dll from this project. The producer and consumer code is not working.

 Does this library supports web ?

**Comment by Nagendra82** [comment]
Hi Jroland,

I am facing similar problem. If I try to copy code from program.cs how can i use in asp.net context. 
Could you please elaborate the proposed solution 'storing producer/consumers in web context. 

Thanks & Regards
Nagendra Singh
