### ISSUE TITLE
Tag Nuget releases

### ISSUE THREAD

**Issue by Xharze** [Jroland/kafka-net#45]
It would be really nice if you could tag the release, which would make it possible to see exactly what each Nuget package contains.

**Comment by Jroland** [comment]
Thanks for the advice, I definitely need to increase my communication of whats being fixed on each deploy.  Ill start tagging the release and getting the release notes into the nuget package.  Any other suggestions?

**Comment by Xharze** [comment]
Sounds good. 
Another suggestion could be regarding the pull requests, there are some very old and very new. Maybe the old ones could be merged or closed, and feedback on the new ones would indicate some project activity.

**Comment by Jroland** [comment]
Ok that release, with notes looks pretty good.  I will make sure I do that from now on.
