### ISSUE TITLE
Producer concurrency issues - TakeAsync method in AsyncCollection class

### ISSUE THREAD

**Issue by marekstachura** [Jroland/kafka-net#60]
We observed that **_TakeAsync_** method (**_AsyncCollection_** class) is not taking into the account the timeout parameter when it is **constantly** getting data from the **_TryTake_** method. 
In our environment we could see that the producer was just building up the batch collection and not returning it, even when the timeout task completed. It returned it only when it reached the batch size (default 100 messages).
For some reason in our case it was taking quite a long time before it reached the batch size (over 60 seconds).

It looks like after introducing additional condition to take into the account the completeness of the  **_timeoutTask_** - it would work as expected.

Please see line:
https://github.com/Jroland/kafka-net/blob/master/src/kafka-net/Common/AsyncCollection.cs#L72

The proposed change could be:
```c#
// Current version, line 72
//[...]
if (--count <= 0) return batch;
//[...]

// Proposed change
//[...]
if (--count <= 0 || timeoutTask.IsCompleted) return batch;
//[...]

```
Looking forward to your opinion about that.

**Comment by Jroland** [comment]
Thanks for the submission, looks like  your solution is good.  I will make the change.

**Comment by marekstachura** [comment]
@Jroland :+1: !
On the feature/integration branch there are more goodies - I've noticed you changed the ConcurrentBag to ConcurrentQueue which should keep the order of the messages, which is nice :)
When do you think will you push new nuget version? 
Thanks!

**Comment by Jroland** [comment]
Yah this is a collection of all the things I have been fixing white using the driver to push large amounts of data around.  Lots of minor tweaks which significantly increases the throughput.  I should be able to get it out tomorrow.
