### ISSUE TITLE
Consumer GetOffset from kafka after restart

### ISSUE THREAD

**Issue by prafash** [Jroland/kafka-net#65]
if i do not save the last offset in the client side, ie if I'm not passing OffsetPosition[] to the Consumer(), Is there any way I can use the kafka-net API to automatically read the saved offset from kafka broker and continue consume where I left off ?  This is helpful to avoid duplicates when my client (consumer ) restart.

**Comment by prafash** [comment]
got it, i'll be creating a highlevel consumer using the offsetcommitrequest and solve my problem.

**Comment by shinurag** [comment]
It would be great if you can share the way of handling the offset.
