### ISSUE TITLE
Create a topic with partitionId

### ISSUE THREAD

**Issue by sanithavk** [Jroland/kafka-net#80]
I would like to create a topic with 1 partition and 1 replication. Is there any method available in Kafka-net

**Comment by Jroland** [comment]
The kafka API does not currently expose the ability for the driver to specify how topics are created.  You have to either...
1. Set your default topic creation settings in the server.properties files of kafka to create new topics with partition 1, replication 1.  
or
2. Pre-create the topic on the server using the command line tools, and set the topic sizes that way.
