### ISSUE TITLE
License

### ISSUE THREAD

**Issue by craigminihan** [Jroland/kafka-net#83]
The LICENSE file shows the (C) for kafka-net is held by David Arthur (this guy? https://github.com/mumrah).

I guess this was a file copy issue and not your intention. 

I need to update the file in my fork with (C) for my changes but I want to make sure it is right before I proceed. What copyright name should I use for the `jroland/kafka-net` contributers?

**Comment by Jroland** [comment]
Ha your right, I just copied the file over, I assumed it was just a generic file.  Ill switch it to me.
